version: "3.9"

services:
  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=arc_bank
    ports:
      - "5434:5432"
    volumes:
      - ./internal/db/data:/var/lib/postgresql/data
